### ISSUE TITLE
Make provider agnostic

### ISSUE THREAD

**Issue by SilentCicero** [coopermaruyama/react-web3#1]
Hey dude, great stuff. I'm planning on integrating a similar pattern for EthJS: https://github.com/ethjs

Would you be able to make this provider agnostic? If so, I can help with abstraction, if not, I'll probably just do my own lib. Regardless, very nice integration!

**Comment by coopermaruyama** [comment]
Can you elaborate? Do you mean decouple the web3-specific logic from react so that it can be used outside react?

**Comment by coopermaruyama** [comment]
@SilentCicero closing this since I haven't heard back - feel free to reopen if needed.
