### ISSUE TITLE
react-web3 not picking up user switching accounts

### ISSUE THREAD

**Issue by spiderbites** [coopermaruyama/react-web3#12]
Hey, thanks for the great package.

I'm finding that the provider is not picking up on account changes initiated via metamask. It seems that the `web3.eth.accounts` is the culprit, which is not getting updated. However the async `web3.eth.getAccounts(...)` version does work.

I'm working on a react app bootstrapped with truffle.  I'm not sure if it's an issue with my app set up or this package.

Cheers

**Comment by tkntobfrk** [comment]
I believe I can confirm this behavior

**Comment by vguzev** [comment]
This is bug in MetaMask. As a workaround use web3.eth.getAccounts for now.
See https://github.com/MetaMask/metamask-extension/issues/2268

**Comment by coopermaruyama** [comment]
Thanks for the heads up. I'll test web3.eth.getAccounts and see if the behavior changes.

**Comment by coopermaruyama** [comment]
Newest version is using getAccounts as of v1
