### ISSUE TITLE
web3@1.0 - 'cb is not a function'

### ISSUE THREAD

**Issue by haydenadams** [coopermaruyama/react-web3#13]
Used to work perfectly, but since upgrading to web3.js 1.0, I get a repeating error (only when using react-web3). 

It still works, but I can't get rid of the error. 

<img width="848" alt="screen shot 2017-11-29 at 11 52 00 pm" src="https://user-images.githubusercontent.com/9343483/33414560-7ded3edc-d560-11e7-8b53-06b970a7db43.png">

**Comment by haydenadams** [comment]
Here's the code:

```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import { Web3Provider } from 'react-web3';

ReactDOM.render(
   <Web3Provider>
      <App />, document.getElementById('root')
   </Web3Provider>
);
```

**Comment by burritofridays** [comment]
I have the same error with the same code.

**Comment by haydenadams** [comment]
Good to hear you found a workaround. I believe thats less safe, since the web3 object can be different in future versions of metaMask. I stopped using this library for now, and made my own splash screen using the following code:

<img width="616" alt="screen shot 2017-12-19 at 10 55 55 pm" src="https://user-images.githubusercontent.com/9343483/34190661-0302132c-e510-11e7-95ca-c3818d109c08.png">

**Comment by coopermaruyama** [comment]
@haydenadams, thanks for this. I'm going to look into this now. My assumption is web3 1.0 has a different API incompatible with this react-web3. Going to see if I can make it work with both.

**Comment by coopermaruyama** [comment]
@haydenadams I have a WIP which has 1 failing test left on web3-v1 branch. Will release soon.

**Comment by coopermaruyama** [comment]
closing this for now in favor of #16
