### ISSUE TITLE
Make compatible with web3 1.0

### ISSUE THREAD

**Issue by coopermaruyama** [coopermaruyama/react-web3#16]

**Comment by coopermaruyama** [comment]
WIP is on branch web3-v1. Close to working, 1 failing test left

**Comment by gtaschuk** [comment]
Looked at that failing test.  A cursory glance seems to indicate that state is being updated when it first mounts, but not subsequently with polling.  If you do `clock.tick(1000)` before the callCount is taken, then it doesn't seem like setState will be called in the 60 seconds thereafter.

**Comment by KamuelaFranco** [comment]
@coopermaruyama Is this now working?

**Comment by coopermaruyama** [comment]
@KamuelaFranco The last failing test is passing now. I haven't yet had a chance to test it in an web3 1.0 app yet though. Will do that ASAP. will be helpful if people can test. For now I'm going to publish on npm as a beta version

**Comment by coopermaruyama** [comment]
web3 1.0 branch published. Install with `npm install react-web3@beta`.
