### ISSUE TITLE
Add in font for no eth account available message

### ISSUE THREAD

**Issue by jefflau** [coopermaruyama/react-web3#2]
I don't have the font for the message so it comes in an ugly default serif font

<img width="764" alt="screen shot 2017-08-04 at 19 13 16" src="https://user-images.githubusercontent.com/1221141/28966519-3db69822-7949-11e7-9561-9eaa57d955a7.png">

**Comment by coopermaruyama** [comment]
Hey, thanks for the heads up. I will update the package today to default to Arial.

**Comment by coopermaruyama** [comment]
This is now fixed in the latest release.
