### ISSUE TITLE
Q: Does the child context mean I no longer have to import web3?

### ISSUE THREAD

**Issue by KamuelaFranco** [coopermaruyama/react-web3#21]
Does `context.web3` provided to children wrapped by the component mean that I do not need to explicitly import `web3` anymore? The full library of commands is available to me now just with `context.web3`?

**Comment by dragosdydy** [comment]
I wonder the same thing. I need to do `new myWeb3.eth.Contract` but it seems my `web3` package is not present anymore in my `node_modules`.

**Comment by afmeirelles** [comment]
This would be nice to confirm.

**Comment by cjol** [comment]
Doesn't look like it: https://github.com/coopermaruyama/react-web3/issues/4

**Comment by coopermaruyama** [comment]
This is not the case. You should still import web3. Otherwise this library would have to assume the node you want to use. Metamask defaults to localhost:8545. This library assumes window.web3 is defined.
