### ISSUE TITLE
Upgrade to React 16.2?

### ISSUE THREAD

**Issue by justinkchen** [coopermaruyama/react-web3#22]
I'm using a higher version of React (16.2) but the peer dependency here isn't being met. Can this be upgraded to React 16.2 as well?

**Comment by guix77** [comment]
Hi, I created an App with create-react-app and I have no issues using react-web3 with it, just to let you know.

**Comment by justinkchen** [comment]
yea i dont think there's any issues, so just want this peer dependency warning to go away

**Comment by Chococoin** [comment]
It works also in React 16.4.2

**Comment by coopermaruyama** [comment]
Fixed in v1.1.1
