### ISSUE TITLE
web3 1.0: MetaMask throws `TypeError: e is not a function` if web3 is imported

### ISSUE THREAD

**Issue by fvictorio** [coopermaruyama/react-web3#25]
Hello, thanks a lot for this component, I like the idea a lot.

I'm trying to use it in a project that uses web3 1.0, but using `react-web3` and also importing and instantiating web3 makes MetaMask throw a lot of `TypeError: e is not a function` errors. I'm not sure if this causes further problems, but is very annoying.

I can create a repo to reproduce the error if you need it.

By the way, where is the code for the 1.0.0 version of this library? None of the branches seem to have it.

Thanks!

**Comment by guix77** [comment]
Hello @fvictorio 

I had this error and got it working (with the 2 PRs) by doing:

`import Web3 from 'web3';
import { Web3Provider } from 'react-web3';
// If the browser has injected Web3.JS
if (window.web3) {
  // Then replace the old injected version by the local Web3.JS version 1.0.0-beta.N
  window.web3 = new Web3(window.web3.currentProvider);
}`

**Comment by coopermaruyama** [comment]
Thanks for the heads up guys. this is fixed
