### ISSUE TITLE
How to detect if a user logout of metamisk?

### ISSUE THREAD

**Issue by thachp** [coopermaruyama/react-web3#30]
Can there be another account creator similar to web3/CHANGE_ACCOUNT but web3/LOGOUT_ACCOUNT?

This is my work around for now..
https://ethereum.stackexchange.com/questions/27366/how-can-i-check-if-a-user-is-logged-in-to-metamask/27368

**Comment by coopermaruyama** [comment]
@thachp I have added support for this in the latest version (v1.1.1)
