### ISSUE TITLE
how can i start project.. 

### ISSUE THREAD

**Issue by 1311pooja** [coopermaruyama/react-web3#33]
there is no scripts to start or run project....
"scripts": {
    "test": "mocha-webpack --webpack-config webpack.config.js --require test/.setup.js test/**/*.test.js",
    "test:watch": "mocha-webpack --watch --webpack-config webpack.config.js --require test/.setup.js test/**/*.test.js",
    "build": "webpack --config webpack.config.js",
    "build:watch": "webpack --config webpack.config.js --watch",
    "prepare": "npm run build"
    
  },

**Comment by coopermaruyama** [comment]
@1311pooja That's because this project has no UI. If you want to use it in your project, just `npm install react-web3` and then in your react file you import it.

Development on the project itself has been done via test cases. Maybe I will add an example file in the future.
