### ISSUE TITLE
No eth account available being displayed for a couple of milliseconds when page is being loaded.

### ISSUE THREAD

**Issue by Cold-A-Muse** [coopermaruyama/react-web3#36]
Is there any way to prevent the component from displaying the 'No eth account available' When the website is initially loaded? Right now it is being displayed for a milliseconds before going to the actual website.

**Comment by coopermaruyama** [comment]
Thanks for the heads up I’ll take a look

**Comment by gohuygo** [comment]
@Cold-A-Muse  Looks like the issue is that we're rendering Web3Provider before handleAccounts is finished. I've opened up a PR - https://github.com/coopermaruyama/react-web3/pull/38. You can take a look for now but I'll have to fix some tests

**Comment by gohuygo** [comment]
Ignore my previous comment, I thought I had fixed the issue but I actually prevented the AccountsUnavailable component from ever rendering.

**Comment by gohuygo** [comment]
@Cold-A-Muse I spent a few hours looking into this but haven't been able to come up with a good solution. It looks like a race condition with Metamask (i.e. even when we are already logged in, the first few calls to Metamask return no accounts). Not sure how to work around this outside of using some kind of setTimeout, but that solution is janky and not 100% reliable.

I have also tried Drizzle (https://github.com/trufflesuite/drizzle) to handle web3 account management but it also suffers the same issue. 

Let me know if you guys come up with a solution

**Comment by gohuygo** [comment]
@Cold-A-Muse  After hacking around a bit with no success, I came across this discussion (https://github.com/MetaMask/metamask-extension/issues/2140) where someone else reported that `web3.eth.account` (which we use in `getAccounts()`) is empty on window load.

It looks like Metamask has changed this based on EIP-1102 specifications (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md) for more user privacy (no longer exposing address to dapps by default). There are some hacks using `setTimeout`, but I am not a fan.

**Comment by mugentime** [comment]
Hi, is this issue still on Gitcoin? If so. I can help you solve it.
