### ISSUE TITLE
How can i use react-redux and Web3Provider both work together?

### ISSUE THREAD

**Issue by kenneth** [coopermaruyama/react-web3#42]
React-Redux use Provider
and i want use Web3Provider
How can i use react-redux and Web3Provider both work together?

**Comment by coopermaruyama** [comment]
You can literally just nest them like this in the root of your app:

```
const MyApp = () => (
  <Provider store={store}>
    <Web3Provider>
       <Stuff />
     </Web3Provider>
  </Provider>
)
```
